/* tslint:disable */
/* eslint-disable */
/**
 * TUBA API
 * TUBA by Jabba ø1 - OpenAPI
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tuba.support@none.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { HealthCheckDto } from '../models/index'
import { HealthCheckDtoFromJSON, HealthCheckDtoToJSON } from '../models/index'

export interface GetHealthRequest {
  xCorrelationId?: any
}

/**
 *
 */
export class GeneralApi extends runtime.BaseAPI {
  /**
   * TUBA Services Status
   */
  async getHealthRaw(
    requestParameters: GetHealthRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<HealthCheckDto>> {
    const queryParameters: any = {}

    const headerParameters: runtime.HTTPHeaders = {}

    if (requestParameters['xCorrelationId'] != null) {
      headerParameters['x-correlation-id'] = String(
        requestParameters['xCorrelationId'],
      )
    }

    const response = await this.request(
      {
        path: `/health`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    )

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      HealthCheckDtoFromJSON(jsonValue),
    )
  }

  /**
   * TUBA Services Status
   */
  async getHealth(
    requestParameters: GetHealthRequest = {},
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<HealthCheckDto> {
    const response = await this.getHealthRaw(requestParameters, initOverrides)
    return await response.value()
  }
}
