/* tslint:disable */
/* eslint-disable */
/**
 * TUBA API
 * TUBA by Jabba ø1 - OpenAPI
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tuba.support@none.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
/**
 *
 * @export
 * @interface UnauthorizedException
 */
export interface UnauthorizedException {
  /**
   * Timestamp of the exception
   * @type {Date}
   * @memberof UnauthorizedException
   */
  timestamp: Date
  /**
   * Trace ID of the request
   * @type {string}
   * @memberof UnauthorizedException
   */
  traceId: string
  /**
   * A unique code identifying the error.
   * @type {number}
   * @memberof UnauthorizedException
   */
  code: UnauthorizedExceptionCodeEnum
  /**
   * Message for the exception
   * @type {string}
   * @memberof UnauthorizedException
   */
  message: string
  /**
   * A description of the error message.
   * @type {string}
   * @memberof UnauthorizedException
   */
  description: string
}

/**
 * @export
 */
export const UnauthorizedExceptionCodeEnum = {
  NUMBER_20001: 20001,
  NUMBER_20002: 20002,
  NUMBER_20003: 20003,
  NUMBER_20004: 20004,
  NUMBER_20005: 20005,
  NUMBER_20006: 20006,
  NUMBER_20007: 20007,
  NUMBER_20008: 20008,
  NUMBER_20009: 20009,
  NUMBER_20010: 20010,
  NUMBER_20011: 20011,
} as const
export type UnauthorizedExceptionCodeEnum =
  (typeof UnauthorizedExceptionCodeEnum)[keyof typeof UnauthorizedExceptionCodeEnum]

/**
 * Check if a given object implements the UnauthorizedException interface.
 */
export function instanceOfUnauthorizedException(value: object): boolean {
  if (!('timestamp' in value)) return false
  if (!('traceId' in value)) return false
  if (!('code' in value)) return false
  if (!('message' in value)) return false
  if (!('description' in value)) return false
  return true
}

export function UnauthorizedExceptionFromJSON(json: any): UnauthorizedException {
  return UnauthorizedExceptionFromJSONTyped(json, false)
}

export function UnauthorizedExceptionFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UnauthorizedException {
  if (json == null) {
    return json
  }
  return {
    timestamp: new Date(json['timestamp']),
    traceId: json['traceId'],
    code: json['code'],
    message: json['message'],
    description: json['description'],
  }
}

export function UnauthorizedExceptionToJSON(
  value?: UnauthorizedException | null,
): any {
  if (value == null) {
    return value
  }
  return {
    timestamp: value['timestamp'].toISOString(),
    traceId: value['traceId'],
    code: value['code'],
    message: value['message'],
    description: value['description'],
  }
}
