/* tslint:disable */
/* eslint-disable */
/**
 * TUBA API
 * TUBA by Jabba ø1 - OpenAPI
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tuba.support@none.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { UserDto } from './UserDto'
import { UserDtoFromJSON, UserDtoFromJSONTyped, UserDtoToJSON } from './UserDto'

/**
 *
 * @export
 * @interface UserSearchResultDto
 */
export interface UserSearchResultDto {
  /**
   * Found User(s) info matching the search criteria
   * @type {Array<UserDto>}
   * @memberof UserSearchResultDto
   */
  user: Array<UserDto>
}

/**
 * Check if a given object implements the UserSearchResultDto interface.
 */
export function instanceOfUserSearchResultDto(value: object): boolean {
  if (!('user' in value)) return false
  return true
}

export function UserSearchResultDtoFromJSON(json: any): UserSearchResultDto {
  return UserSearchResultDtoFromJSONTyped(json, false)
}

export function UserSearchResultDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserSearchResultDto {
  if (json == null) {
    return json
  }
  return {
    user: (json['user'] as Array<any>).map(UserDtoFromJSON),
  }
}

export function UserSearchResultDtoToJSON(value?: UserSearchResultDto | null): any {
  if (value == null) {
    return value
  }
  return {
    user: (value['user'] as Array<any>).map(UserDtoToJSON),
  }
}
