/* tslint:disable */
/* eslint-disable */
/**
 * TUBA API
 * TUBA by Jabba ø1 - OpenAPI
 *
 * The version of the OpenAPI document: 1.0
 * Contact: tuba.support@none.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime'
import type { UserAccountNewDto } from './UserAccountNewDto'
import {
  UserAccountNewDtoFromJSON,
  UserAccountNewDtoFromJSONTyped,
  UserAccountNewDtoToJSON,
} from './UserAccountNewDto'

/**
 *
 * @export
 * @interface UserUpdDto
 */
export interface UserUpdDto {
  /**
   * User display name, or first name.
   *
   * If not specified, a default one will be generated from the associated account(s).
   * @type {string}
   * @memberof UserUpdDto
   */
  name?: string
  /**
   * Optional user last / family name.
   * @type {string}
   * @memberof UserUpdDto
   */
  nameLast?: string
  /**
   * User profile type
   * @type {string}
   * @memberof UserUpdDto
   */
  type?: UserUpdDtoTypeEnum
  /**
   * User associated sub-accounts: crypto wallet account (EOA), email, social network, oauth2, etc
   * @type {Array<UserAccountNewDto>}
   * @memberof UserUpdDto
   */
  account?: Array<UserAccountNewDto>
}

/**
 * @export
 */
export const UserUpdDtoTypeEnum = {
  Individual: 'individual',
  Business: 'business',
} as const
export type UserUpdDtoTypeEnum =
  (typeof UserUpdDtoTypeEnum)[keyof typeof UserUpdDtoTypeEnum]

/**
 * Check if a given object implements the UserUpdDto interface.
 */
export function instanceOfUserUpdDto(value: object): boolean {
  return true
}

export function UserUpdDtoFromJSON(json: any): UserUpdDto {
  return UserUpdDtoFromJSONTyped(json, false)
}

export function UserUpdDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): UserUpdDto {
  if (json == null) {
    return json
  }
  return {
    name: json['name'] == null ? undefined : json['name'],
    nameLast: json['nameLast'] == null ? undefined : json['nameLast'],
    type: json['type'] == null ? undefined : json['type'],
    account:
      json['account'] == null
        ? undefined
        : (json['account'] as Array<any>).map(UserAccountNewDtoFromJSON),
  }
}

export function UserUpdDtoToJSON(value?: UserUpdDto | null): any {
  if (value == null) {
    return value
  }
  return {
    name: value['name'],
    nameLast: value['nameLast'],
    type: value['type'],
    account:
      value['account'] == null
        ? undefined
        : (value['account'] as Array<any>).map(UserAccountNewDtoToJSON),
  }
}
